---
description: Creates stacks for my imaginary service
vars:
  ENV_LABEL: bijay
  ENV_TYPE: nonproduction
  SUB_SYSTEM: iam
  SERVICE_NAME: imaginary-service
  AWS_PROFILE: sputnik-pre-staging
jobs:
  Infra:
    description: "imaginary service job"
    stacks:
      SNSStack:
        template_file: "templates/nop.yml"
        stack_name: "{{ .ENV_LABEL }}-sns-stack"
        parameters: 
          EnvironmentType: '{{ .ENV_TYPE }}'
          EnvironmentName: '{{ .ENV_LABEL }}'
        tags:
          EnvironmentType: '{{ .ENV_TYPE }}'
          EnvironmentName: '{{ .ENV_LABEL }}'
        # retry: 10 ## For retries https://stackoverflow.com/questions/69343418/can-we-configure-retry-attempts-on-aws-go-sdk-service-calls
        # timeout: 10

      SQSStack:
        template_file: "templates/nop.yml"
        stack_name: "{{ .ENV_LABEL }}-sqs-stack"
        capabilities:
          - CAPABILITY_IAM
          - CAPABILITY_NAMED_IAM
        parameters:
          EnvironmentType: '{{ .ENV_TYPE }}'
          EnvironmentName: '{{ .ENV_LABEL }}'
        tags:
          EnvironmentType: '{{ .ENV_TYPE }}'
          EnvironmentName: '{{ .ENV_LABEL }}'
  services:
    description: "imaginary service job"
    stacks:
      idmservice:
        template_file: "templates/nop.yml"
        stack_name: "{{ .ENV_LABEL }}-oauth2-service"
        capabilities:
          - CAPABILITY_IAM
          - CAPABILITY_NAMED_IAM
        parameters:
          EnvironmentType: '{{ .ENV_TYPE }}'
          EnvironmentName: '{{ .ENV_LABEL }}'
        tags:
          EnvironmentType: '{{ .ENV_TYPE }}'
          EnvironmentName: '{{ .ENV_LABEL }}'

      idmlambda:
        enable_change_set: true
        template_file: "templates/nop.yml"
        stack_name: "{{ .ENV_LABEL }}-service"
        capabilities:
          - CAPABILITY_IAM
          - CAPABILITY_NAMED_IAM
        parameters:
          EnvironmentType: '{{ .ENV_TYPE }}'
          EnvironmentName: '{{ .ENV_LABEL }}'
        tags:
          EnvironmentType: '{{ .ENV_TYPE }}'
          EnvironmentName: '{{ .ENV_LABEL }}'

      changeset:
        needs: idmservice
        template_file: "templates/nop.yml"
        stack_name: "{{ .ENV_LABEL }}-change-set"
        capabilities:
          - CAPABILITY_IAM
          - CAPABILITY_NAMED_IAM
        parameters:
          EnvironmentType: '{{ .ENV_TYPE }}'
          EnvironmentName: '{{ .ENV_LABEL }}'
        tags:
          EnvironmentType: '{{ .ENV_TYPE }}'
          EnvironmentName: '{{ .ENV_LABEL }}'
  Lambdas:
    description: "imaginary service job"
    stacks:
      SNSStack:
        template_file: "templates/nop.yml"
        stack_name: "{{ .ENV_LABEL }}-sqs-consumer"
        parameters: 
          EnvironmentType: '{{ .ENV_TYPE }}'
          EnvironmentName: '{{ .ENV_LABEL }}'
        tags:
          EnvironmentType: '{{ .ENV_TYPE }}'
          EnvironmentName: '{{ .ENV_LABEL }}'
        # retry: 10 ## For retries https://stackoverflow.com/questions/69343418/can-we-configure-retry-attempts-on-aws-go-sdk-service-calls
        # timeout: 10