Parameters:
  EnvironmentType:
    Type: String
  EnvironmentName:
    Type: String
  VpcId:
    Type: String

Resources:
  CfnComposeSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub "CfnCompose test security group for ${EnvironmentType}"
      VpcId: !Ref VpcId
      Tags:
        - Key: EnvironmentName
          Value: !Ref EnvironmentName
        - Key: EnvironmentType
          Value: !Ref EnvironmentType

Outputs:
  SecurityGroupId:
    Value: !Ref CfnComposeSecurityGroup
    Export:
      Name: !Sub ${EnvironmentName}:CfnComposeSecurityGroupId
