Description: Sample CloudFormation Compose file
Vars:
  DelaySeconds: "60"
  ENV_NAME: cfn-compose
  ENV_TYPE: nonproduction
  SUBNET_ID: "subnet-03ac1d211789419dd"
  VPC_ID: "vpc-0a023fdf39152a210"
  AWS_PROFILE: "demo"
Flows:
  EC2Instance:
    Description: Creates EC2 Instance Security Group
    Stacks:
    - template_file: sg.yml
      stack_name: sample-{{ .ENV_NAME }}-security-group
      parameters:
        EnvironmentName: '{{ .ENV_NAME }}'
        EnvironmentType: '{{ .ENV_TYPE }}'
        VpcId: '{{ .VPC_ID }}'
      tags:
        EnvironmentName: '{{ .ENV_NAME }}'
        EnvironmentType: '{{ .ENV_TYPE }}'
    - template_file: ec2.yml
      stack_name: sample-{{ .ENV_NAME }}-ec2-instance
      parameters:
        EnvironmentName: '{{ .ENV_NAME }}'
        EnvironmentType: '{{ .ENV_TYPE }}'
        SubnetId: '{{ .SUBNET_ID }}'
      tags:
        EnvironmentName: '{{ .ENV_NAME }}'
        EnvironmentType: '{{ .ENV_TYPE }}'
    Order: 1
  MessageQueue:
    Description: Deploying Queuing Resources
    Stacks:
    - template_file: sqs.yml
      stack_name: sample-{{ .ENV_NAME }}-sqs
      parameters:
        DelaySeconds: '{{ .DelaySeconds }}'
        EnvironmentName: '{{ .ENV_NAME }}'
        EnvironmentType: '{{ .ENV_TYPE }}'
      tags:
        EnvironmentName: '{{ .ENV_NAME }}'
        EnvironmentType: '{{ .ENV_TYPE }}'
    Order: 1
