Parameters:
  EnvironmentType:
    Type: String
  EnvironmentName:
    Type: String
  DelaySeconds:
    Type: Number
Resources:
  CfnComposeQueue:
    Type: AWS::SQS::Queue
    Properties:
      DelaySeconds: !Ref DelaySeconds
      Tags:
        - Key: EnvironmentName
          Value: !Ref EnvironmentName
        - Key: EnvironmentType
          Value: !Ref EnvironmentType

