Parameters:
  EnvironmentType:
    Type: String
  EnvironmentName:
    Type: String
  DelaySeconds:
    Type: Number
Conditions:
  Never:
    !Equals [ "A", "C" ]

Resources:
  NonResource:
    Type: AWS::SQS::Queue
    Properties:
      DelaySeconds: !Ref DelaySeconds
    Condition: Never

