Parameters:
  EnvironmentType:
    Type: String
  EnvironmentName:
    Type: String
  SubnetId:
    Type: String
  ImageId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
  InstanceType:
    Type: String
    Default: t2.nano
Resources:
  ExampleEC2Instance: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
        - Fn::ImportValue: !Sub ${EnvironmentName}:CfnComposeSecurityGroupId
      Tags:
        - Key: EnvironmentName
          Value: !Ref EnvironmentName
        - Key: EnvironmentType
          Value: !Ref EnvironmentType