Parameters:
  EnvironmentType:
    Type: String
  EnvironmentName:
    Type: String
Conditions:
  Never:
    !Equals [ "A", "C" ]

Resources:
  NonResource:
    Type: Custom::NonResource
    Properties:
      One: "key"
    Condition: Never

  TestSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub "TestSecurityGroup for ${EnvironmentType} of type ${EnvironmentType}"
      VpcId:
        Fn::ImportValue: balman:VPC
